# Site settings
title: Design Wall Template
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "./" # the base hostname & protocol for your site
baseurl: '/designwall/'
logo: 'img/logo.png'

# Build settings
markdown: kramdown


navigation:
  - home:
    url: '/'
    title: 'Home'
  - About:
    url: 'about-us.html'
    title: 'About us'
  - Contact:
    url: 'contact.html'
    title: 'Contact'



social_icons: true
#the below work if the social_icons is true
social:
 - Facebook:
   url: 'http://facebook.com'    
   icon_class: 'icon-facebook'
 - Twitter:
   url: 'http://twitter.com'    
   icon_class: 'icon-twitter'
 - GooglePlus:
   url: 'http://google.com'    
   icon_class: 'icon-google-plus'
 - Youtube:
   url: 'http://youtube.com'    
   icon_class: 'icon-youtube'
 - Linkedin:
   url: 'http://linkedin.com'    
   icon_class: 'icon-linkedin'
 - Vimeo:
   url: 'http://github.com'    
   icon_class: 'icon-github'

# the whole icons classes you can find here: http://fortawesome.github.io/Font-Awesome/icons/
