# Site settings
title: Design Wall Template
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "./" # the base hostname & protocol for your site
baseurl: ''
logo: '/img/logo.png'

# Build settings
markdown: kramdown
paginate: 10

# read more text
more_text: 'Continue reading'

# Related articles text udner the post
rel_art_text: 'Related Articles.'

# the name for posts
author-name-text: 'My Name'

#menu item text
home-page-text: 'Home'

#social icons
social-facebook: '#'
social-twitter: '#'
social-google-plus: '#'
social-youtube: '#'
social-linkedin: '#'

#small ads
small-ad1-img: '/img/add1.gif'
small-ad1-url: '#'

small-ad2-img: '/img/add1.gif'
small-ad2-url: '#'

small-ad3-img: '/img/add1.gif'
small-ad3-url: '#'

small-ad4-img: '/img/add1.gif'
small-ad4-url: '#'


#big ad
big-ad-img: '/img/big_add.jpg'
big-ad-url: '#'

#footer text and link
footer-powered-by-text: 'Proudly powered by'
footer-powered-by-url: '#'
footer-powered-by-title: 'Jekyll template'
