# Site settings
title: Design Wall Template
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "./" # the base hostname & protocol for your site
baseurl: '/designwall'
logo: '/img/logo.png'

# Build settings
markdown: kramdown
paginate: 10

more_text: 'Continue reading'
rel_art_text: 'Related Articles.'
author-name:
  text: My Name

navigation:
  - home:
    url: '/'
    title: 'Home'
  - About:
    url: '/about-us.html'
    title: 'About us'
  - Contact:
    url: '/contact.html'
    title: 'Contact'



social_icons: true
#the below work if the social_icons is true
social:
 - Facebook:
   url: 'http://facebook.com'    
   icon_class: 'icon-facebook'
 - Twitter:
   url: 'http://twitter.com'    
   icon_class: 'icon-twitter'
 - GooglePlus:
   url: 'http://google.com'    
   icon_class: 'icon-google-plus'
 - Youtube:
   url: 'http://youtube.com'    
   icon_class: 'icon-youtube'
 - Linkedin:
   url: 'http://linkedin.com'    
   icon_class: 'icon-linkedin'



small-ads:
 - ad1:
   url: '#'
   img: '/img/add1.gif'
 - ad2:
   url: '#'
   img: '/img/add1.gif'

 - ad3:
   url: '#'
   img: '/img/add1.gif'

 - ad3:
   url: '#'
   img: '/img/add1.gif'


big-ad:
  url: '#'
  img: '/img/big_add.jpg'

footer-powered-by:
 text: 'Proudly powered by'
 url: '#'
 title: 'Design Wall'